version: '3'
services:
  instagram-backend:
    depends_on:
      - mongo
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./
    volumes:
      - ./node_modules:/instagram-backend/node_modules
      - ./:/instagram-backend
    stdin_open: true
    environment:
      CHOKIDAR_USEPOLLING: 'true'
    ports:
      - '5000:5000'
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    environment:
      MONGO_INITDB_DATABASE: instagram
    volumes:
      - ~/mongo/data:/data/db
    ports:
      - 27017:27017
