version: '3'
services:
  instagram-backend:
    build:
      dockerfile: Dockerfile
      context: ./
    volumes:
      - ./node_modules:/instagram-backend/node_modules
      - ./:/instagram-backend
    stdin_open: true
    environment:
      - DB_PROD=${DB_PROD}
    ports:
      - '5000:5000'
